name: EC2 Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Title
        run: echo '### Server Deploy! :fire:' >> $GITHUB_STEP_SUMMARY

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ec2-54-207-238-175.sa-east-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            # Remove old files and kill old processes
            pm2 delete all 
            kill -9 $(lsof -t -i:3000)
            rm -rf ezops-test-gabrielbello

            # Clone repo
            git clone https://github.com/gabrielfbello/ezops-test-gabrielbello.git
            cd ezops-test-gabrielbello

            # MongoDB Connection
            touch .env
            echo 'MONGO_URL=${{ secrets.MONGO_URL }}' >> .env

            # Install dependencies and build
            npm install
            npm run build

            pm2 start dist/main.js --name api-server
