name: EC2 Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Workflow
        run: echo '### Server Deploy! :fire:' >> $GITHUB_STEP_SUMMARY

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: b3llo
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: b3llo/ezops:latest

      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ec2-15-228-9-206.sa-east-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            sudo netstat -pna | grep 3000
            docker pull b3llo/ezops:latest
            docker container run -d --name ezops --restart always -p 3000:3000 b3llo/ezops:latest
